### ISSUE TITLE
QuasselDroid update on Google Play Store

### ISSUE THREAD

**Issue by Reverite** [sandsmark/QuasselDroid#230]
The release on the Google Play Store is v0.9.8, is there any possibility of uploading the newest version to the Play Store?

**Comment by justjanne** [comment]
The latest version will be uploaded to the Play Store as soon as all bugs have been fixed, for now it’s in the beta available through the Store if you join our beta community at https://plus.google.com/communities/104094956084217666662

**Comment by TomLottermann** [comment]
What exactly is the blocker for pushing new versions in Play Store?
My device policy prohibits me from installing Apps from unknown sources.

**Comment by justjanne** [comment]
@TomLottermann: the only thing blocking us from releasing a new version is that all our efforts are on building the next next version, and no one (well, I'm alone in this project anyway) has found time (and access — the play store account still belongs to a previous developer) to fix all the bugs in the current beta build, and release it. That's why we only distribute it as Google Play Beta (join the Google+ community to gain access to it) or as apk.

It's just not ready, and we can't make it ready yet.
