### ISSUE TITLE
Add offline push notification

### ISSUE THREAD

**Issue by Fale** [sandsmark/QuasselDroid#241]
Please, do create a way so if you are mentioned and you have no clients connected to the server, your phone (and/or other android device) receives a push notification, so you can open the app and read/reply, without killing your phone keeping the app open all day long

**Comment by aziraphale** [comment]
This is something that I know people have looked in to before, but I believe the current thinking is that it would require a modification on the core to support it, which is something people are trying to avoid.

That said, I guess it might be possible to create a separate client that stayed connected to the core and sent notifications when necessary. Huge amount of work, though.

**Comment by Fale** [comment]
Why a modification to the core is something that people are trying to avoid?

**Comment by sandsmark** [comment]
the plan is to add core-side scripting in Quassel, so that people can do all kinds of stuff like this (not everyone uses the same devices, or even services for push notifications, for example, and some people might want to send SMSes or whatever).


the biggest issue is that at the moment it is the client that checks for highlights (for a bunch of arbitrary reasons, as well as because people are running the core on potatoes). so that would at least have to be changed first. it just isn't something that anyone has cared enough about to implement yet (patches welcome etc.).
