### ISSUE TITLE
notify on other text [Feature request]

### ISSUE THREAD

**Issue by rubinlinux** [sandsmark/QuasselDroid#249]
Would be nice if you honored the highlight settings so that you can be highlighted for things besides just your active nick.
quassel-client has options to be notified on any of your identity's nicks, or arbitrary strings (with regex even). It would be handy.  Thanks-

**Comment by aziraphale** [comment]
FYI, the custom highlight settings are stored *on the client* rather than on the core (yeah, it's not very helpful, but that's what we have to work with :)), so this can only (currently) be implemented as a *separate* list of custom highlight strings - you'd have to enter them all again, and keep them in sync manually.
