### ISSUE TITLE
Feature Requests: open first unread message first

### ISSUE THREAD

**Issue by fernandog** [sandsmark/QuasselDroid#252]
As the title: when open channel show first unread message instead of last message posted
thanks!

**Comment by fernandog** [comment]
Thanks!!

**Comment by justjanne** [comment]
Misunderstood the request based on what was said in IRC:

Actual issue here: No ability to automatically jump to first unread message upon opening the channel.

Possible implementation: A separate setting, only possible if user sets "load all unread messages", that sets the "last chat position" to the markerline.

**Comment by fernandog** [comment]
@justjanne 
"load all unread messages" - don't QD always load all unread messages? Im confused.

Existing setting:
"Unread messager per chat" - Fetch all unseen messages on connect  ON|OFF
Are you saying to add a sub-setting to this one?

**Comment by justjanne** [comment]
correct.

Quasseldroid, by default, only loads around the last 20 messages.

the idea would be a setting that if you have "load all unread" selected, it would automatically jump to the top the first time you open a channel.

**Comment by fernandog** [comment]
nice! thanks! Our github organization uses irc and they talk a lot there lol
